apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-test
  template:
    metadata:
      labels:
        app: scale-test
    spec:
      containers:
      - name: busybox
        image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
        command: ["sh", "-c", "while true; do nslookup kubernetes.default.svc.cluster.local; sleep 2; done"]
