kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ebpf-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
      - containerPort: 30080
        hostPort: 8081
        protocol: TCP
    extraMounts:
      - hostPath: /lib/modules
        containerPath: /lib/modules
        readOnly: true
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        readOnly: false

  - role: worker
    extraMounts:
      - hostPath: /lib/modules
        containerPath: /lib/modules
        readOnly: true
      - hostPath: /sys/fs/bpf
        containerPath: /sys/fs/bpf
        readOnly: false

networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
