apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: service-a-redirect
  namespace: test-services
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: service-a
      namespace: test-services
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: service-b
    toPorts:
      - name: http-failover
        port: "5001"
        protocol: TCP
